<?php
/**
 * Created by IntelliJ IDEA.
 * User: frankhildebrandt
 * Date: 24.04.13
 * Time: 16:21
 * To change this template use File | Settings | File Templates.
 */

namespace SectorNord\Transport\ActiveMQ;

class Server extends \SectorNord\Transport\Server
{

    /** @var \Stomp */
    protected $amq;

    protected $replyQueue;

    protected $correlationId;

    function __construct($zmqSocket, $queue, $service)
    {
        $this->queue = $queue;
        parent::__construct($zmqSocket, $service); // TODO: Change the autogenerated stub
    }

    protected function initServer()
    {
        $this->amq = new \Stomp($this->socket);
        $this->amq->subscribe($this->queue);
    }

    protected function receiveMessage()
    {
        while (!($queueObject = $this->amq->readFrame())) {
        }
        $this->replyQueue = $queueObject->headers['reply-to'];
        $this->correlationId = $queueObject->headers['correlation-id'];

        $msg = $queueObject->body;
        $this->amq->ack($queueObject);
        return $msg;
    }

    protected function postMessage($response)
    {
        $this->amq->send($this->replyQueue, $response, array('correlation-id' => $this->correlationId));
    }
}